services:

  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: services/cli
    environment:
      - AI_ASSISTANT=${AI_ASSISTANT}

  redis:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: redis
